### ISSUE TITLE
(sc-test-full)

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken-RTs#3]
l. 274

(write-antescofo... is 5304, so fails the > 5500 test

**Comment by mdedwards** [comment]
hmmm I get 5510:

"/tmp/slippery.asco.txt" 
Antescofo~ score written successfully with 949 events and 4561 actions.
5510 

we should get the same output. how many events/actions do you get?

Can you attach the generated /tmp/slippery.asco.txt file so I can do a diff?

**Comment by danieljamesross** [comment]
Well that's odd, it's now outputting the same as yours, i.e. what's expected.

**Comment by mdedwards** [comment]
OK so I'll close the issue
