### ISSUE TITLE
TEST-WEBPAGE-RSP-RSM-RTHM-SEQ-PALETTE)

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken-RTs#4]
I tried to run a full test but (TEST-WEBPAGE-RSP-RSM-RTHM-SEQ-PALETTE) failed.

I ran it in isolation and got:
    Testing: (TEST-WEBPAGE-RSP-RSM-RTHM-SEQ-PALETTE)...
    Generating rthm-seqs...
    Calling cmn...
    T

Just ran the full test again, having not changed anything, and it passed. 

Is there something odd about (file-write-ok) or (probe-delete)  on my Mac?

**Comment by mdedwards** [comment]
hmm that's weird...i made minor changes last night to file-write-ok but that shouldn't affect you...if anything it should now be more robust. 

do git pull to see the changes if you like...or maybe do a pull again then run the full tests. 

closing now as this seems to no longer be an issue.
