### ISSUE TITLE
(TEST-EVENT-WRITE-XML)

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken-RTs#5]
This fails on sc-test-suite.lsp on alternative runs. I.e. I run it, it fails, I run it again without changing anything and then it passes.

**Comment by danieljamesross** [comment]
In fact, it's not quite alternative goes, it's after I run the FULL test.

1. run full test
2. test passes
3. run test-suite
4. test fails
5. re-run test (without changes)
6. test passes

**Comment by mdedwards** [comment]
Dare I say RTFM?:::::: "There are two main files that can be loaded into Lisp once it has been freshly started and slippery-chicken loaded: sc-test-suite.lsp and sc-test-full.lsp. Be sure not to run one after the other, in either direction, unless you've restarted Lisp."

Or are you restarting Lisp between those steps?

**Comment by danieljamesross** [comment]
No, I wasn't and no I didn't RTFM. Magic all good then!

**Comment by mdedwards** [comment]
but did you RTFM now? ;;;))))

**Comment by danieljamesross** [comment]
NEVER!

**Comment by mdedwards** [comment]
OK. So all future issues/requests ignored. Gotcha.

**Comment by danieljamesross** [comment]
😂
