### ISSUE TITLE
test fails for me

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken-RTs#6]
https://github.com/mdedwards/slippery-chicken-RTs/blob/0d29fa3eb798f1318fc8ddbffa2fa1efaccf6336/sc-test-suite.lsp#L15759

The function `parse-audacity-label-file-for-loops` returns something like: "313 markers, 0 loops read" but not the large list the test function is looking for.

**Comment by mdedwards** [comment]
weird, I fixed one just like that last week...thought they were now all working...anyway, did it (again?)
