### ISSUE TITLE
This line fails the test for me.

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken-RTs#7]
https://github.com/mdedwards/slippery-chicken-RTs/blob/24c0d1ea6486e16af113e0372e3e40419165f5da/sc-test-suite.lsp#L8342

Have latest sc/michael and RTs

**Comment by mdedwards** [comment]
you sure you got the latest src? because I did change the cc order for ped^ and that passes for me

**Comment by danieljamesross** [comment]
defo




*Daniel James Ross*
vitruviandan.wordpress.com

**Comment by mdedwards** [comment]
so line 567+ of event.lsp goes:

           ;; MDE Sat Sep 28 16:36:05 2019 -- changed the order as no longer
           ;; working when reversed 
           (ped^ (pedal 0) (pedal 127))

you updated the michael branch right?

**Comment by danieljamesross** [comment]
Yeah, that's what I've got




*Daniel James Ross*
vitruviandan.wordpress.com

**Comment by mdedwards** [comment]
strange. and line 8341 of sc-test-suite.lsp is

        ;; MDE Mon Sep 30 15:15:48 2019 -- changed order of pedals
        (cc= 2 2 '((1 64 127) (1 64 0)))

**Comment by danieljamesross** [comment]
hmmm, odd. They're the other way around for me but my git status says it is
up to date.




*Daniel James Ross*
vitruviandan.wordpress.com

**Comment by mdedwards** [comment]
but that's the order at the top of this issue

**Comment by danieljamesross** [comment]
I just referenced the line No., didn't check against the online code, presumed it was the same because my git said it was up to date.

Anyhoo, deleted my local code and re-downloaded, passes now.

Wonder why git confused?

**Comment by mdedwards** [comment]
no idea

**Comment by danieljamesross** [comment]
updating my git, hopefully that'll sort things. I guess there was some weird cache thing as I had a few minor formatting tweaks that made my branch different.

**Comment by mdedwards** [comment]
ok
